import datetime
import importlib.util
import os

import psycopg
import pytest

from conftest import DATABASE_NUMBERS, UTC, make_track
from smarter_playlists import library

spec = importlib.util.spec_from_file_location(
    'import_history', os.path.join(os.path.dirname(__file__), '..', 'scripts', 'import_history.py'))
import_history = importlib.util.module_from_spec(spec)
spec.loader.exec_module(import_history)

OLD_SCHEMA = """
    CREATE TABLE artist (artist_id BIGINT PRIMARY KEY, artist_name TEXT NOT NULL);
    CREATE TABLE album (album_id BIGINT PRIMARY KEY, album_name TEXT NOT NULL, artist_id BIGINT NOT NULL,
                        release_year INT);
    CREATE TABLE track (track_id BIGINT PRIMARY KEY, track_name TEXT NOT NULL, length BIGINT NOT NULL,
                        album_id BIGINT NOT NULL, artist_id BIGINT NOT NULL, play_count INT NOT NULL,
                        last_played TIMESTAMP, date_added TIMESTAMP, track_number INT NOT NULL, itunes_id TEXT,
                        bpm INT, loved BOOLEAN NOT NULL);
    CREATE TABLE play (play_id BIGINT GENERATED BY DEFAULT AS IDENTITY, track_id BIGINT, played_at TIMESTAMP NOT NULL);
"""

LAST_PLAYED = datetime.datetime(2026, 8, 8, 19, 18, 46, tzinfo=UTC)


def at(text):
    return datetime.datetime.fromisoformat(text).replace(tzinfo=UTC)


@pytest.fixture
def history(postgres, empty_database):
    """An old database, with .track() and .play() to fill it."""
    name = 'history_{0}'.format(next(DATABASE_NUMBERS))
    with psycopg.connect(dbname='postgres', autocommit=True) as admin:
        admin.execute('CREATE DATABASE {0}'.format(name))
    with psycopg.connect(dbname=name) as db:
        db.execute(OLD_SCHEMA)

    class History:
        def __init__(self):
            self.name = name
            self.next_id = 1

        def track(self, title='Weird Fishes / Arpeggi', artist='Radiohead', album='In Rainbows', play_count=0,
                  last_played=None, plays=()):
            track_id = self.next_id
            self.next_id += 1
            with psycopg.connect(dbname=name) as db:
                db.execute("INSERT INTO artist VALUES (%s, %s)", [track_id, artist])
                db.execute("INSERT INTO album VALUES (%s, %s, %s, NULL)", [track_id, album, track_id])
                db.execute("INSERT INTO track VALUES (%s, %s, 1000, %s, %s, %s, %s, NULL, 1, %s, NULL, FALSE)",
                           [track_id, title, track_id, track_id, play_count, last_played,
                            'OLD{0:013X}'.format(track_id)])
                for played_at in plays:
                    db.execute("INSERT INTO play (track_id, played_at) VALUES (%s, %s)", [track_id, played_at])
            return track_id

    yield History()
    with psycopg.connect(dbname='postgres', autocommit=True) as admin:
        admin.execute('DROP DATABASE {0} WITH (FORCE)'.format(name))


@pytest.fixture
def run(database_name, history, monkeypatch):
    """Imports the given library tracks, with the history underneath."""
    def run(*tracks):
        monkeypatch.setattr(library, 'read_library', lambda: list(tracks))
        import_history.import_with_history(database_name, history.name)
    return run


def plays(query, track_id='A000000000000001'):
    return [(played_at.astimezone(UTC), estimated) for played_at, estimated in query(
        "SELECT played_at, estimated FROM play WHERE track_id = %s ORDER BY played_at", [track_id])]


def test_keeps_real_plays_and_drops_ones_that_werent(history, run, query):
    history.track(play_count=3, last_played=datetime.datetime(2021, 6, 1, 20, 0), plays=[
        datetime.datetime(1904, 1, 1, 1, 0),           # bogus
        datetime.datetime(2020, 3, 1, 2, 15),          # real, early on the 1st
        datetime.datetime(2020, 10, 24, 19, 0),        # real
        datetime.datetime(2020, 10, 24, 20, 0),        # recorded again when the clocks changed
        datetime.datetime(2021, 6, 1, 20, 0),          # real
    ])
    run(make_track(play_count=3, last_played_at=at('2021-06-01T20:00:00')))

    assert plays(query) == [(at('2020-03-01T02:15:00'), False), (at('2020-10-24T19:00:00'), False),
                            (at('2021-06-01T20:00:00'), False)]


def test_keeps_monthly_backfill_estimates(history, run, query):
    history.track(play_count=5, last_played=datetime.datetime(2020, 2, 10, 12, 0), plays=[
        datetime.datetime(2019, 11, 1, 0, 0, 0), datetime.datetime(2019, 11, 1, 0, 0, 1),
        datetime.datetime(2020, 1, 1, 6, 0, 5),
        datetime.datetime(2020, 1, 20, 9, 30),
        datetime.datetime(2020, 2, 10, 12, 0),
    ])
    run(make_track(play_count=5, last_played_at=at('2020-02-10T12:00:00')))

    assert plays(query) == [(at('2019-11-01T00:00:00'), True), (at('2019-11-01T00:00:01'), True),
                            (at('2020-01-01T06:00:05'), True), (at('2020-01-20T09:30:00'), False),
                            (at('2020-02-10T12:00:00'), False)]


def test_spreads_year_end_backfill_evenly_from_2010(history, run, query):
    history.track(play_count=5, last_played=datetime.datetime(2019, 5, 1, 12, 0), plays=[
        datetime.datetime(2018, 12, 31, 23, 59, 0), datetime.datetime(2018, 12, 31, 23, 59, 1),
        datetime.datetime(2018, 12, 31, 23, 59, 2),
        datetime.datetime(2019, 3, 1, 12, 0),
        datetime.datetime(2019, 5, 1, 12, 0),
    ])
    run(make_track(play_count=5, last_played_at=at('2019-05-01T12:00:00')))

    rows = plays(query)
    first_real = at('2019-03-01T12:00:00')
    gap = (first_real - library.HISTORY_START) / 4
    assert rows == [(library.HISTORY_START + gap * n, True) for n in (1, 2, 3)] + [
        (first_real, False), (at('2019-05-01T12:00:00'), False)]


def test_plays_since_are_spread_from_the_last_old_play(history, run, query):
    history.track(play_count=2, last_played=datetime.datetime(2021, 6, 1, 20, 0), plays=[
        datetime.datetime(2021, 5, 1, 20, 0), datetime.datetime(2021, 6, 1, 20, 0)])
    run(make_track(play_count=6, last_played_at=LAST_PLAYED))

    rows = plays(query)
    assert len(rows) == 6
    old_last = at('2021-06-01T20:00:00')
    gap = (LAST_PLAYED - old_last) / 4
    assert rows[2:] == [(old_last + gap * n, True) for n in (1, 2, 3)] + [(LAST_PLAYED, False)]


def test_unplayed_since_is_not_recorded_twice(history, run, query):
    # The library can report the same last played time an hour out
    history.track(play_count=2, last_played=datetime.datetime(2021, 6, 1, 20, 0), plays=[
        datetime.datetime(2021, 5, 1, 20, 0), datetime.datetime(2021, 6, 1, 20, 0)])
    run(make_track(play_count=2, last_played_at=at('2021-06-01T19:00:00')))

    assert len(plays(query)) == 2


def test_matches_tracks_by_name(history, run, query):
    history.track(title='WEIRD FISHES / ARPEGGI', artist='radiohead', album='in rainbows', play_count=1,
                  last_played=datetime.datetime(2021, 1, 1, 12, 0), plays=[datetime.datetime(2021, 1, 1, 12, 0)])
    history.track(title='Nude', album='Old Album Name', play_count=1,
                  last_played=datetime.datetime(2021, 1, 2, 12, 0), plays=[datetime.datetime(2021, 1, 2, 12, 0)])
    history.track(title='Reckoner', album='Somewhere Else', play_count=1,
                  last_played=datetime.datetime(2021, 1, 3, 12, 0), plays=[datetime.datetime(2021, 1, 3, 12, 0)])
    history.track(title='Gone', play_count=1, last_played=datetime.datetime(2021, 1, 4, 12, 0),
                  plays=[datetime.datetime(2021, 1, 4, 12, 0)])
    run(make_track(track_id='A000000000000001'),
        make_track(track_id='A000000000000002', title='Nude'),
        # Reckoner is in the library twice, on other albums, so can't be told apart
        make_track(track_id='A000000000000003', title='Reckoner', album_id='C000000000000002', album_title='One'),
        make_track(track_id='A000000000000004', title='Reckoner', album_id='C000000000000003', album_title='Two'))

    assert query("SELECT track_id, count(*) FROM play GROUP BY 1 ORDER BY 1") == [
        ('A000000000000001', 1), ('A000000000000002', 1)]


def test_merges_old_duplicates_of_a_track(history, run, query):
    for played_at in (datetime.datetime(2020, 1, 5, 12, 0), datetime.datetime(2020, 2, 5, 12, 0)):
        history.track(play_count=2, last_played=played_at, plays=[played_at])
    run(make_track(play_count=4, last_played_at=at('2020-02-05T12:00:00')))

    rows = plays(query)
    assert len(rows) == 4
    assert [row for row in rows if not row[1]] == [(at('2020-01-05T12:00:00'), False),
                                                   (at('2020-02-05T12:00:00'), False)]


def test_refuses_a_database_already_imported_into(history, run, run_import):
    run_import(make_track(play_count=1, last_played_at=LAST_PLAYED))

    with pytest.raises(SystemExit, match='before the first import'):
        run(make_track(play_count=1, last_played_at=LAST_PLAYED))
